css: ".button {\r\n  display: inline-block;\r\n  border: 2px;\r\n  padding: 3px 8px;\r\n}"
headingLevels:
  - 2
  - 3
  - 4
name: 'Full Text'
options:
  alignment:
    options:
      - left
      - center
      - right
      - justify
  highlight:
    options:
      -
        class: marker-green
        color: var(--ck-highlight-marker-green)
        model: greenMarker
        title: 'Green marker'
        type: marker
      -
        class: pen-red
        color: var(--ck-highlight-pen-red)
        model: redPen
        title: 'Red pen'
        type: pen
  style:
    definitions:
      -
        classes:
          - knockout
        element: h3
        name: 'Knockout (H3)'
      -
        classes:
          - marker
        element: span
        name: Marker
      -
        classes:
          - button
        element: a
        name: Button
toolbar:
  - heading
  - alignment
  - '|'
  - link
  - bold
  - italic
  - '|'
  - style
  - '|'
  - bulletedList
  - numberedList
  - todoList
  - '|'
  - blockQuote
  - horizontalLine
  - outdent
  - indent
