defaultPlacement: end
fieldLayouts:
  ffd7180f-b459-439b-ad4b-886354fee5d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: a735e918-67de-47b8-b478-8b97f11e8c97
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 26465f40-52f6-4cc9-b0fc-c7ed2e996b01
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 117070d4-2b99-40d3-8e50-2bf2293c4b5d
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: d563e642-5a45-44df-ad86-711f8457abf2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 30ab686c-9e4b-46ea-8913-3e1050df15fa
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 3fa91ef2-d942-4ef0-9149-8ae9fe7b37e3
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 00c83f3a-d38c-4769-9cef-c3bd9501bb17
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: d648b6aa-01ef-4f2c-b016-84729b17b3c2
        userCondition: null
handle: utility
instructions: ''
maxNodes: null
name: Utility
permissions:
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions:
      - 'section:83a6e4e2-3e52-435e-bcb4-ced4dc7e387e' # Taxonomies
      - 'section:4688dcb4-257f-4a94-b8b7-db234f63e0a9' # Landing Pages
      - 'section:247cf34e-12cf-4324-b034-3209f48a18ff' # Page Content
      - 'section:b1ee8bc9-827b-4fec-943c-c6ff229adb59' # Articles
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  d34bee8e-bf22-451d-8339-a4342630833d: # Craft CMS
    enabled: true
sortOrder: 3
structure:
  maxLevels: 1
  uid: 310ae1f7-dddd-4711-b139-5bf36c981f8a
