columnSuffix: null
handle: code
instructions: null
name: Code
searchable: true
settings:
  availableLanguages:
    - css
    - dockerfile
    - graphql
    - html
    - javascript
    - json
    - markdown
    - mysql
    - php
    - python
    - shell
    - twig
    - typescript
    - yaml
  codeFolding: false
  defaultValue: ''
  fontSize: 18
  language: twig
  lineNumbers: true
  monacoEditorOptions: ''
  placeholder: ''
  showLanguageDropdown: true
  singleLineEditor: false
  theme: vs-dark
translationKeyFormat: null
translationMethod: none
type: nystudio107\codefield\fields\Code
