columnSuffix: null
handle: collections
instructions: null
name: Collections
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Choose Collection'
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:667ee826-8732-4bc8-8dbe-b7aefad82b15' # Collections
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
