columnSuffix: null
handle: headline
instructions: null
name: Headline
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: d794ad1d-257e-41a6-a11e-6e0c66406d07 # Headline
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
