columnSuffix: null
handle: headerBuilder
instructions: null
name: 'Header Builder'
searchable: true
settings:
  createButtonLabel: 'Header Builder'
  entryTypes:
    - 14dff90f-f8fc-444e-bc75-e51f72aa490d # Text
    - 68c9259f-a4a4-41f4-a0d3-74ae1164ac80 # Code
    - 4248eeb1-ca4d-476f-9998-7780ee611c74 # Image
    - 96192f21-960f-489c-a380-96e4b51f2777 # Card Deck
    - b4783a60-e9ff-40a2-8e9e-159b24fad0a9 # Media
    - faaa512e-f0ed-4151-97de-d73bdc9a4f5e # Component
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
