columnSuffix: null
handle: summary
instructions: null
name: Summary
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: ef0d77ed-a6ab-49db-afe4-2be38730d402 # Description
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: 100
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
