columnSuffix: null
handle: taxonomies
instructions: null
name: 'Topics & Tags'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Choose Topic'
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:83a6e4e2-3e52-435e-bcb4-ced4dc7e387e' # Taxonomies
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
