columnSuffix: null
handle: toc
instructions: null
name: 'Table of Contents'
searchable: true
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Label
            -
              - handle
              - label
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Slug
            -
              - handle
              - slug
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Level
            -
              - handle
              - level
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - '0'
                    -
                      - value
                      - '0'
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - '1'
                    -
                      - value
                      - '1'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '2'
                    -
                      - value
                      - '2'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '3'
                    -
                      - value
                      - '3'
                    -
                      - default
                      - false
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
