columnSuffix: null
handle: variant
instructions: null
name: Variant
searchable: false
settings:
  columnType: null
  configFile: _config/_variant.json.twig
translationKeyFormat: null
translationMethod: none
type: simplicateca\selectplus\fields\SelectPlusField
