columnSuffix: null
handle: website
instructions: null
name: 'Website / Content URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
