defaultPlacement: end
enableVersioning: true
entryTypes:
  - 40f8a572-f12e-49f2-849d-8fbe3395eb5c # Addon
handle: addons
maxAuthors: 1
name: Addons
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d34bee8e-bf22-451d-8339-a4342630833d: # Craft CMS
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
