defaultPlacement: end
enableVersioning: true
entryTypes:
  - ff76eb70-820e-4752-b138-daef62692e3f # Block Fragments
handle: fragments
maxAuthors: 1
name: Fragments
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d34bee8e-bf22-451d-8339-a4342630833d: # Craft CMS
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
