defaultPlacement: end
enableVersioning: true
entryTypes:
  - bb561dd8-e748-4c68-9107-2ffd5db410d8 # Topic
  - 8b83b1c6-3917-4365-bc67-1f94599cbb08 # Private Tag
handle: taxonomy
maxAuthors: 1
name: Taxonomies
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d34bee8e-bf22-451d-8339-a4342630833d: # Craft CMS
    enabledByDefault: true
    hasUrls: true
    template: _site/taxonomy._entry.twig
    uriFormat: '{% from ''_site/taxonomy._entry'' import uri %}{{ uri( object ) }}'
structure:
  maxLevels: 2
  uid: cc00ceed-0937-472c-b55c-c83fa5fce262
type: structure
