color: null
fieldLayouts:
  b4b38964-c1af-4fb1-93cf-932474e3f431:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _sitehub/ui-template-header-builder.twig
            type: craft\fieldlayoutelements\Template
            uid: 64d82312-b911-43af-b992-5809f8b97968
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Preview Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aedc1aa3-6210-41c6-ad77-bad9e5d8d7b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Expanded Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e743afee-7020-4ff0-9cbd-a0fefb4bcd22
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Header Builder
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db86d482-84f8-4c29-9298-e1c92b207c86
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0cd8cbb4-1f0e-433d-9eba-6a9b63f6e954
            userCondition: null
          -
            elementCondition: null
            template: _sitehub/ui-template-body-builder.twig
            type: craft\fieldlayoutelements\Template
            uid: 8522f80f-641c-4488-859d-e2f2be1c2ff7
            userCondition: null
            width: 25
          -
            elementCondition: null
            fieldUid: b4753be4-da84-4306-82e8-a9473ca5398f # Body Builder
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 258bd87d-fe05-4864-9b6b-ff4242737748
            userCondition: null
            warning: null
            width: 75
        name: 'Main Content'
        uid: 3c3155c1-5a06-4af0-9133-a225c6fc3481
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _sitehub/ui-template-sidebar-builder.twig
            type: craft\fieldlayoutelements\Template
            uid: 669889b0-01cc-4e90-9ef8-93dfdcc34f8c
            userCondition: null
            width: 50
          -
            elementCondition: null
            fieldUid: a6272176-e780-4d5e-90f2-df0115d1a324 # Sidebar Builder
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acb9db84-b9c2-4dc4-8ba2-e74d4b77ddde
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 230a2d7e-c3b4-470b-98d8-ebae7d2a045e
            userCondition: null
          -
            elementCondition: null
            fieldUid: 9be9dfbd-e578-410f-ad06-8b7a6e9a0734 # Table of Contents
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 861b5a7e-1717-4b7a-8f47-72abfa668c9a
            userCondition: null
            warning: null
            width: 100
        name: 'Secondary Content'
        uid: aad52856-3589-4f41-bdaf-babdf64fe217
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7646e467-2a81-4a85-9048-5c1c08c0f6b6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8d0681a-5357-41e5-8f9f-a3734374352c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 909ea097-5d1c-446d-a47b-e71b8d458715
            userCondition: null
          -
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics & Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d91a561-496c-4838-a76e-4755733d6667
            userCondition: null
            warning: null
            width: 100
        name: 'Meta Details'
        uid: a382a529-7f5e-4679-bd22-ecf6344f8285
        userCondition: null
handle: article
hasTitleField: true
icon: newspaper
name: Article
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
