color: null
fieldLayouts:
  322a0f34-1814-4e8d-a8e7-6095f590bb43:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b3fc6df1-5abe-4bcd-abc3-274ccb9da0a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Presentation'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ff2269f-1a61-4e6d-bcd0-dd05430035c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: 1fc4d14e-bdf2-4cfa-a95c-64f6dac73d40 # Collections
                  layoutElementUid: 4d783d12-81c6-4dd3-9fc4-0c2e79f64c99
                  operator: empty
                  uid: c348fb79-1430-4c06-976b-e829fe54540f
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39adec54-ab28-4bf4-84a9-c01b591629d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
                  layoutElementUid: 39adec54-ab28-4bf4-84a9-c01b591629d5
                  operator: empty
                  uid: 027b9de0-f7e6-496d-a82c-39939bfe64ab
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 1fc4d14e-bdf2-4cfa-a95c-64f6dac73d40 # Collections
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d783d12-81c6-4dd3-9fc4-0c2e79f64c99
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 518032ea-dbb4-44fb-b190-8057f4fd6666
            userCondition: null
          -
            elementCondition: null
            fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Content Layout
            handle: null
            includeInCards: false
            instructions: null
            label: 'Supporting Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db8622f2-0ec9-4de4-9f76-a2954648b67c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\MatrixFieldConditionRule
                  operator: in
                  uid: 8607f88c-8f5d-4cdf-911a-81b5e377c76a
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Header Builder
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Headline
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e30da91e-928a-429a-81ed-33da2acbabad
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\MatrixFieldConditionRule
                  operator: ni
                  uid: 74bfac06-c9d1-48c2-9346-2e236c45cced
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Header Builder
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7487ca3f-f51b-40e9-a538-40ab5b2c4a27 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10d999b9-f82d-4901-9c85-ae49b141c26b
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3fe218e9-3dc0-4b55-b29e-367c5b1e6532
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5635a1ac-adca-4a96-816a-7ae1b664bc4d # Theme & Scenery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9315debe-db4b-41f4-9b86-ab4b6861eb14
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3383902d-5fd0-4eb5-b3cb-d5798e3a4aad
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
