color: null
fieldLayouts:
  0043a478-7bc5-4a6f-b717-de689da18143:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8f8c6d9e-ccae-4474-b5a9-278798c778e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
            handle: null
            includeInCards: false
            instructions: null
            label: 'Media Presentation'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36cfdd17-7a79-4f5a-b45f-46ded5796f39
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: a186d4ae-477e-4b06-868e-add5e8f44b0c # Embeds
                  layoutElementUid: 8fc2b388-4ba3-49d8-9911-34a4eb7f889b
                  operator: empty
                  uid: 80fe7cc2-db43-436f-88d8-40c86f8dedd2
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: 1fc4d14e-bdf2-4cfa-a95c-64f6dac73d40 # Collections
                  layoutElementUid: 9aff22c7-e3ba-4cdd-b1c3-d6555df62b50
                  operator: empty
                  uid: 92b09fb6-d50f-4bd6-a614-6bf81257f88e
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: d8bf6768-4ff5-4727-ac20-12f8f0344542 # Media
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd9863d6-70f6-4b2f-a1bb-98f5cf9bf95b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: a186d4ae-477e-4b06-868e-add5e8f44b0c # Embeds
                  layoutElementUid: 8fc2b388-4ba3-49d8-9911-34a4eb7f889b
                  operator: empty
                  uid: b19eded2-e323-47af-9509-242a0ee18688
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: d8bf6768-4ff5-4727-ac20-12f8f0344542 # Media
                  layoutElementUid: cd9863d6-70f6-4b2f-a1bb-98f5cf9bf95b
                  operator: empty
                  uid: e8dd305e-1d80-4859-94d6-222adf053664
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 1fc4d14e-bdf2-4cfa-a95c-64f6dac73d40 # Collections
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9aff22c7-e3ba-4cdd-b1c3-d6555df62b50
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: 1fc4d14e-bdf2-4cfa-a95c-64f6dac73d40 # Collections
                  layoutElementUid: 9aff22c7-e3ba-4cdd-b1c3-d6555df62b50
                  operator: empty
                  uid: 3695e92f-eda4-499c-90f0-c8ee3f19566c
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: d8bf6768-4ff5-4727-ac20-12f8f0344542 # Media
                  layoutElementUid: cd9863d6-70f6-4b2f-a1bb-98f5cf9bf95b
                  operator: empty
                  uid: e44c8369-ffae-4f67-98b0-ca3712895066
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: a186d4ae-477e-4b06-868e-add5e8f44b0c # Embeds
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fc2b388-4ba3-49d8-9911-34a4eb7f889b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9ca7bce8-bd92-4dba-8a3c-665119b81813
            userCondition: null
          -
            elementCondition: null
            fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Content Layout
            handle: null
            includeInCards: false
            instructions: null
            label: 'Supporting Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58d78c0e-d03a-414b-8ab1-4fcb72befed0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\MatrixFieldConditionRule
                  operator: in
                  uid: 101a3de8-3daf-4b22-aa75-391ac9000b17
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Header Builder
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Headline
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bca2240-b2e2-4ad4-b086-0f816c44ee12
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\MatrixFieldConditionRule
                  operator: ni
                  uid: 788f9638-e43a-4ee9-a502-9aec554c2f62
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Header Builder
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7487ca3f-f51b-40e9-a538-40ab5b2c4a27 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9526c500-4357-4b56-bef9-d88b8e65cf0b
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 93f7cab4-6cf5-445b-834b-7444e7cfcdfe
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5635a1ac-adca-4a96-816a-7ae1b664bc4d # Theme & Scenery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f61f5747-389a-4042-8d5f-6c9ccb33b5df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 408a25d4-998d-45d3-a875-c9038a60f203
        userCondition: null
handle: media
hasTitleField: false
icon: tv-retro
name: Media
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
