color: null
fieldLayouts:
  45b00d8c-3b6b-402f-a5e2-7730f8446a4e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cdbab99b-eea2-48e8-a08b-175972b868a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23057663-5e25-472e-ae93-bd532cc227e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b150cb8-953c-4382-a298-eb2269a566ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 50d14e2f-06b6-4473-a89c-3172686194f9
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdef433a-36cb-4ebd-880d-613a302d09b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0db6ebbc-5805-4c79-9564-c3e75297a359 # Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f399cdd-16a9-471d-8f1a-f8de432254e4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 774ec15a-ed72-484e-8174-b6504d4c6aac
        userCondition: null
handle: pattern
hasTitleField: true
icon: flask
name: Pattern
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
