color: null
fieldLayouts:
  89296a1c-5559-43a3-8dea-a125ac30a48c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cb1b3b49-5006-4f9f-86ae-28fb646636c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            template: _sitehub/ui-template-body-builder.twig
            type: craft\fieldlayoutelements\Template
            uid: 17bb8c0a-8953-40af-ab17-861ae72ce6a2
            userCondition: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4753be4-da84-4306-82e8-a9473ca5398f # Body Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dac46000-c32b-4af3-b74d-4d643d9d4ac3
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: a6272176-e780-4d5e-90f2-df0115d1a324 # Sidebar Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7387dd0a-0963-496c-b7f7-97ecb6fbfa69
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 7b6cfbc4-41c9-44e2-a7d6-41b9edf2286f
        userCondition: null
handle: reusable
hasTitleField: true
icon: shutters
name: 'Block Fragments'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
