color: null
fieldLayouts:
  88a546fc-9281-41ec-95ed-067b8189e823:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _sitehub/ui-template-collection.twig
            type: craft\fieldlayoutelements\Template
            uid: 6bf895f4-35be-4982-b3a6-3ec91a9dc746
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Collection Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ffd4f14a-5ac2-4c78-a29f-5917a566ca3b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 4c042122-01b4-4dcc-9378-8d5b8cd30d57
            userCondition: null
          -
            elementCondition: null
            fieldUid: d554a8e7-e8ad-493b-aaa8-d611bf04b257 # Website / Content URL
            handle: null
            includeInCards: false
            instructions: null
            label: 'Feed URL'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63d0e682-3bfb-4034-b833-278852df1c47
            userCondition: null
            warning: null
            width: 50
        name: 'Primary Content'
        uid: 6d0ed962-3faa-419f-a748-bcdbc5ff55a3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Expanded Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dedfb61b-8dd0-4bd1-a235-070e2978abb8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b54aca1f-5631-4f76-a248-e953c4ada5bd # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2be36c0-3439-48b6-8569-1f8b06de889b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 581b9070-f50c-49a0-91c7-2921437ad0fb # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cd14e89-921f-4bd3-b0de-9d0a9c9d4e8a
            userCondition: null
            warning: null
            width: 25
        name: 'Meta Details'
        uid: e1addfa2-41e0-451f-abd5-58c5bae2eaac
        userCondition: null
handle: rss
hasTitleField: true
icon: rss
name: 'RSS Feed'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
